### PR TITLE
fix chunked body reading

### PR DESCRIPTION
**Pull request by mhils**
This PR fixes the chunked body reading, which would previously fail when confronted with invalid bodies.

### CODE REVIEW

**Comment by jbremer** [comment]
Could you add a pcap and unittest for this issue? I believe the tests can only be run in the Git repository and not as part of the Python package (it wouldn't make sense to ship .pcap files in a Python package anyway). It can be invoked with `httpreplay test`.

**Comment by mhils** [comment]
I can't really disclose the pcap, sorry. It basically boils down to `int(line, 16)` throwing a ValueError if confronted with something non-inty. Shall we just add a test for that?

**Comment by jbremer** [comment]
Fine by me :-)

**Comment by mhils** [comment]
Added tests.

**Comment by jbremer** [comment]
Thanks!

**Pull request merged**
